version: 2
jobs:
  build:
    working_directory: ~/AustinCodingAcademy/web-workbook
    docker:
    - image: circleci/node:8.9.4
    steps:
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-gh-pages-
        - v1-dep-
    - run: npm install
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules
    - run: npm run lint
